theme: minima
plugins: [jekyll-feed]
sass:
  style: compressed



title: Michał Szostek – Hardware Portfolio
description: Senior Hardware / Electronics Engineer – PCB Design & Embedded Systems

author:
  name: Michał Szostek
  email: your@email.com

header_pages:
  - index.md
  - projects.md
  
show_excerpts: false
